## Backup cronjob configuration
## Ref: https://github.com/maorfr/kube-tasks
backup:
  enabled: false
  componentName: "backup"
  schedule: "0 2 * * *"
  labels: {}
  annotations: {}
  image:
    repository: "maorfr/kube-tasks"
    tag: "0.2.0"
  extraArgs: []
  existingSecret: {}
  env: []
  resources:
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi
      cpu: 1
  destination: "s3://jenkins-data/backup"
checkDeprecation: true
