master:
  JCasC:
    configScripts:
      freestyle-jobs: |
        jobs:
          - script: >
              job('Triggered') {
                parameters {
                  fileParam('build.properties')
                }
                steps {
                  copyArtifacts('Triggeranotherjob')
                  environmentVariables {
                    propertiesFile('build.properties')
                  }
                  shell('echo $PASSWORD;cat build.properties')
                }
              }
          - script: >
              job('Triggeranotherjob') {
                wrappers {
                  credentialsBinding {
                    string('PASSWORD','PASSWORD')
                  }
                }
                steps {
                  shell('echo PASSWORD=$PASSWORD > build.properties;cat build.properties')
                }
                publishers {
                  archiveArtifacts('build.properties')
                  downstreamParameterized {
                    trigger('Triggered') {
                      condition('SUCCESS')
                      parameters {
                        propertiesFile('build.properties', true)
                      }
                    }
                  }
                }
              }
