master:
  JCasC:
    enabled: true
    defaultConfig: true
    configScripts: {}
    securityRealm: |-
      local:
        allowsSignup: false
        users:
         - id: ken
           name: Ken
           description: "Da Man"
           password: testpass
           properties:
            - mailer:
                emailAddress: "test@example.com"
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
