master:
  JCasC:
    enabled: true
    defaultConfig: true
    configScripts: {}
    securityRealm: |-
      legacy
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
