master:
  JCasC:
    configScripts:
      theme-settings: |
        unclassified:
          simple-theme-plugin:
            elements:
              - cssText:
                  text: |-
                    .pipeline-new-node {
                        display: none;
                    }
