master:
  JCasC:
    configScripts:
      simple-theme-plugin:
        elements:
          - cssText:
              text: |-
                .pipeline-new-node {
                    display: none;
                }
