controller:
  JCasC:
    configScripts:
      example-password: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                - string:
                    description: "Example Password credential"
                    id: "PASSWORD"
                    scope: GLOBAL
                    secret: ${test}
