controller:
  componentName: "jenkins-controller"
  disableRememberMe: false
  markupFormatter: plainText
  customJenkinsLabels: []
  adminSecret: true
  securityRealm: |-
    <securityRealm class="hudson.security.LegacySecurityRealm"/>
  authorizationStrategy: |-
     <authorizationStrategy class="hudson.security.FullControlOnceLoggedInAuthorizationStrategy">
       <denyAnonymousReadAccess>true</denyAnonymousReadAccess>
     </authorizationStrategy>
  hostNetworking: false
  jenkinsHome: "/var/jenkins_home"
  jenkinsRef: "/usr/share/jenkins/ref"
  rollingUpdate: {}
  usePodSecurityContext: true
  runAsUser: 1000
  fsGroup: 1000
  servicePort: 8080
  targetPort: 8080
  serviceAnnotations: {}
  deploymentLabels: {}
  serviceLabels: {}
  podLabels: {}
  agentListenerPort: 50000
  agentHostPort:
  cli: false
  agentListenerServiceType: "ClusterIP"
  agentListenerServiceAnnotations: {}
  agentDefaultsProviderTemplate: ""
  agentConnectTimeout: 5
  agentReadTimeout: 15
  agentKubernetesNamespace:
  agentJenkinsUrl:
  agentJenkinsTunnel:
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  extraPorts: []
  initializeOnce: false
  overwritePluginsFromImage: true
  enableRawHtmlMarkupFormatter: false
  scriptApproval: []
  customInitContainers: []
  nodeSelector: {}
  terminationGracePeriodSeconds:
  tolerations: []
  podAnnotations: {}
  deploymentAnnotations: {}
  hostAliases: []
  testEnabled: true
