controller:
  installPlugins:
    - adoptopenjdk:1.3
    - apache-httpcomponents-client-4-api:4.5.13-1.0
    - bootstrap4-api:4.6.0-3
    - bouncycastle-api:2.20
    - branch-api:2.6.3
    - build-user-vars-plugin:1.6
    - cloudbees-folder:6.15
    - command-launcher:1.4
    - conditional-buildstep:1.4.1
    - config-file-provider:3.8.0
    - configuration-as-code:1.47
    - copyartifact:1.45.1
    - credentials-binding:1.24
    - credentials:2.3.18
    - dark-theme:0.0.10
    - display-url-api:2.3.4
    - docker-plugin:1.2.0
    - durable-task:1.36
    - echarts-api:5.1.0-2
    - email-ext:2.77
    - envinject:2.3.0
    - font-awesome-api:5.15.2-2
    - git-client:3.7.1
    - git-server:1.9
    - git:4.7.1
    - github:1.31.0
    - github-api:1.123
    - gradle:1.36
    - greenballs:1.15
    - h2-api:1.4.199
    - handlebars:3.0.8
    - htmlpublisher:1.23
    - jackson2-api:2.12.3
    - jdk-tool:1.4
    - job-dsl:1.77
    - jquery-detached:1.2.1
    - jquery3-api:3.6.0-1
    - jsch:0.1.55.2
    - junit:1.49
    - kubernetes:1.29.0
    - kubernetes-client-api:4.13.3-1
    - kubernetes-credentials:0.8.0
    - lockable-resources:2.10
    - mailer:1.34
    - matrix-project:1.18
    - maven-plugin:3.10
    - momentjs:1.1.1
    - parameterized-trigger:2.39
    - pipeline-build-step:2.13
    - pipeline-graph-analysis:1.10
    - pipeline-input-step:2.12
    - pipeline-maven:3.9.3
    - pipeline-milestone-step:1.3.2
    - pipeline-model-api:1.8.4
    - pipeline-model-definition:1.8.4
    - pipeline-model-extensions:1.8.4
    - pipeline-rest-api:2.19
    - pipeline-stage-step:2.5
    - pipeline-stage-tags-metadata:1.8.4
    - pipeline-utility-steps:2.6.1
    - pipeline-stage-view:2.19
    - plain-credentials:1.7
    - plugin-util-api:2.1.0
    - run-condition:1.5
    - scm-api:2.6.4
    - script-security:1.76
    - simple-theme-plugin:0.6
    - slack:2.42
    - snakeyaml-api:1.27.0
    - ssh-credentials:1.18.1
    - ssh-slaves:1.31.5
    - structs:1.22
    - timestamper:1.11.5
    - token-macro:2.15
    - trilead-api:1.0.13
    - workflow-aggregator:2.6
    - workflow-api:2.42
    - workflow-basic-steps:2.23
    - workflow-cps-global-lib:2.19
    - workflow-cps:2.90
    - workflow-durable-task-step:2.38
    - workflow-job:2.40
    - workflow-multibranch:2.23
    - workflow-scm-step:2.12
    - workflow-step-api:2.23
    - workflow-support:3.8
